name: D2 Processing and S3 Upload

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different
  pull_request:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  process-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # To be able to get the changed files

    - name: Install d2
      run: |
        curl -fsSL https://d2lang.com/install.sh | sh -s --
        echo "$HOME/.d2/bin" >> $GITHUB_PATH

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: '**/*.d2'  # Only consider .d2 files

    - name: Process changed files and upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'  # Change this to your desired region
        S3_LOCATION: ${{ secrets.S3_LOCATION }}
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Processing $file"
          output_file="${file%.*}.svg"
          d2 --theme=300 --dark-theme=200 -l elk --pad 0 "$file" "$output_file"
          aws s3 cp "$output_file" $S3_LOCATION
        done

